apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "standardnotes.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "standardnotes.name" . }}
      release: {{ .Release.Name }}
      component: db
  template:
    metadata:
      labels:
        app: {{ include "standardnotes.name" . }}
        release: {{ .Release.Name }}
        component: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image }}"
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.db.environment.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.db.environment.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.db.environment.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.db.environment.MYSQL_PASSWORD }}"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "standardnotes.fullname" . }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "standardnotes.fullname" . }}-db
spec:
  selector:
    app: {{ include "standardnotes.name" . }}
    component: db
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  type: ClusterIP