apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "standardnotes.fullname" . }}-db-pvc
spec:
  accessModes:
    -  {{ .Values.db.pvc.accessModes | quote  }}
  resources:
    requests:
      storage: {{.Values.db.pvc.storage}}